version: '3.7'

services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8088:8081
    networks:
      - epl
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
      
  football:
    image: seanhong2000/football
    build: .
    command: sh -c "cd football && python premier.py"
    volumes:
      - .:/app
    networks:
      - epl
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ec2-3-34-48-86.ap-northeast-2.compute.amazonaws.com:8001/epl/"]
      interval: 20s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M

  fastapi:
    image: seanhong2000/football
    container_name: fastapi
    build: .
    container_name: football_api
    command: sh -c "cd app && python main.py"
    restart: always
    volumes:
      - .:/app
    ports:
      - 8008:8000
    networks:
      - epl
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ec2-3-34-48-86.ap-northeast-2.compute.amazonaws.com:8001/rank"]
      interval: 20s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M

# volume 설정.
volumes:
  mongo-storage:
# networks 
networks:
  epl:
    external:
        name: mon_net 
